### ISSUE TITLE
关于简介中的文字错误，以及是否自动延迟大厅

### ISSUE THREAD

**Issue by MetaHF** [lakwsh/l4dtoolz#1]
请问
在简介中的2.3动态移除大厅指令应该是
sv_unreserved而不是sv_unreserve 吗？

动态移除大厅是否是自动的，若不是自动的
是否为 
若移除大厅，输入动态移除大厅指令，恢复大厅
若为移除大厅，输入动态移除大厅指令，移除大厅

期待您的回复

**Comment by lakwsh** [comment]
感谢提醒，指令确实是sv_unreserved，这个问题会在下一次更新修正。
至于移除大厅功能，目前是手动的（也暂时没有计划改成自动，因为原意是判断条件可以根据用户的需求通过编写插件的方式调用指令，例如条件是服务器满了4人或者8人）
目前移除大厅功能只能移除大厅，不能恢复大厅（因为没确认过恢复大厅是否有效果），后面有空我会测试一下，如果可行会实现相关功能！
