### ISSUE TITLE
[修改請求] 與其他Tickrate插件做區別處理

### ISSUE THREAD

**Issue by fbef0102** [lakwsh/l4dtoolz#13]
您好，我看了說明書知道啟動選項不寫-tickrate 就不會生效
但因為我想裝其他人的tickerate enabler
像是這位作者已經更新版本，可以修改128 tick: [accelerator74/Tickrate-Enabler](https://github.com/accelerator74/Tickrate-Enabler)
他的tickrate enabler也要設置啟動選項```-tickrate xx```，如果寫了```-tickrate xx```，兩個extension功能同時運作互相衝突

所以我的需求是: 希望新增一個指令可以開關Tickrate解鎖功能

謝謝您

**Comment by lakwsh** [comment]
因爲tickrate解鎖功能部分設定需要在伺服器啓動之初進行，因此通過指令方式控制tickrate解鎖功能開關在技術上會存在一定困難（需要引入額外偏移/簽名）。較爲便捷的實現方式為添加額外啓動項，在檢測到該啓動項時不啓用tickrate解鎖相關功能，但爲了不啓用tickrate解鎖而引入額外啓動項有點奇怪...，對於這個需求我需要額外時間考慮是否及如何實施。如有需要，我建議你fork倉庫並自行修改源代碼，將代碼中[`g_tickrate`](https://github.com/lakwsh/l4dtoolz/blob/main/l4dtoolz.cpp#L241)的值固定為30。

**Comment by fbef0102** [comment]
嗯，感謝答覆
我有另一種方式提供思路
將啟動選項```-tickrate```改名，以便於與其他的tickrate extension作品分開

當然如果改名掉，會讓之前已經使用的玩家感到麻煩，給你參考

**Comment by lakwsh** [comment]
這也是一種處理方法，但代價有點大，應該不會採用…
至於100+（如128）tick時的客戶端＆伺服器不同步問題，當初我對伺服器二進制文件進行反向工程時其實有關注到：起源引擎有對客戶端tick值上限有做限制（如CGameClient::SetUpdateRate函數，限制值為100）。由於未能確認其他位置是否也有相似限制，且為減少使用的偏移/簽名數量，故未有做適配，如有需要可以補上。

**Comment by fbef0102** [comment]
行吧，你的extension 相較於其他人的作品，減少了玩家無故掉線（no steam logon）的愚蠢問題，自從今年5月更新之後，掉線更加嚴重了。

我想知道為什麼當初重製l4dtoolz，要順便寫tickrate，兩者有什麼關聯性嗎？

P.S. 我也看得懂簡體字

**Comment by lakwsh** [comment]
要話關聯性，其實係兩者實現的功能上並不大，but係功能實現個方式上很相似（本質都是對伺服器內存打patch…）
促使我將l4dtoolz和tickrate_enabler二合一的根本原因在於，tickrate_enabler本身實現解鎖tickrate功能個代碼邏輯過於複雜，而l4dtoolz對內存進行補丁的代碼亦完全可以復用與tickrate上。
（btw，繁體字也是我母語之一）

**Comment by fbef0102** [comment]
恩，了解
如果實現我的需求太麻煩那關閉此issue

想在另外問一個跟這個issue無關的問題，
我看到你有插件l4d2_unreservelobby，也是跟其他人的作品不一樣
"模式滿人時自動unreserve server，當沒有滿人時恢復reserve server"

我其實很想知道恢復大廳後會有大廳的原本效果?（吸引路人匹配）

**Comment by lakwsh** [comment]
據實驗結果而言，若果大廳創建者仍在同一伺服器中進行遊戲，伺服器人數超出大廳人數上限移除大廳後一段時間內（具體有幾耐不清楚；若創建者離開遊戲，時間可能縮短）恢復大廳，大廳仍有原本效果。但若果大廳已經失效而伺服器恢復大廳，可能出現“會話不可用”提示，且其他玩家無法進入伺服器。
該插件使用場景建議為：單輪遊戲（遊戲開始至所有玩家離開伺服器）時常不超過3～4小時的伺服器。

**Comment by fbef0102** [comment]
看起來這大廳機制都很迷，反正只要能吸引到路人匹配就好

我的需求只有你的l4dtoolz可以關閉或固定g_tickrate
跟其他tickrate enbler作品共用
甚麼方法都可以

**Comment by fbef0102** [comment]
> 但若果大廳已經失效而伺服器恢復大廳，可能出現“會話不可用”提示，且其他玩家無法進入伺服器。

經過長時間測試，確實如你所說
如果steam master那邊的cookie已經失效
即使伺服器這裡強制改回sv_lobby_cookie "xxxxxx" 會沒用
還會導致“會話不可用”提示，其他玩家無法進入伺服器。

unreserved之後
有經過五分鐘就馬上失效，也有經過三小時才失效的

這大廳匹配機制迷
