### ISSUE TITLE
使用你的l4dtoolz需要删除其它版本的l4dtoolz吗

### ISSUE THREAD

**Issue by zzy-plus** [lakwsh/l4dtoolz#14]
![image](https://github.com/user-attachments/assets/e370c2c2-39f4-41cd-8902-f77c1e454801)
这个是别人的l4dtoolz，和你的同时安装在服务器中，启动无报错，但是使用tickrate解锁功能时出现问题。
四个rate的值分别为：20 50 100 30

**Comment by lakwsh** [comment]
该版本的l4dtoolz包含多人解锁及Tick解锁功能，建议删除其他版本l4dtoolz及tickrate_enabler。
另外，使用tick解锁功能时出现问题的具体现象是什么？
