### ISSUE TITLE
Tick解锁功能需要额外修改的Cvar项

### ISSUE THREAD

**Issue by lakwsh** [lakwsh/l4dtoolz#15]
仅以100Tick为例，**没有提到的Cvar与Tick解锁功能无关**
请在服务端**启动项**加入`-tickrate 100`，然后**server.cfg**文件写入以下内容

> fps_max 999
> net_splitrate 2
> net_splitpacket_maxrate 200000
> sm_cvar sv_minupdaterate 100
> sm_cvar sv_maxupdaterate 100
> sv_mincmdrate 100
> sv_maxcmdrate 100
> sm_cvar nb_update_frequency 0.01
> sm_cvar sv_client_min_interp_ratio 0
> sm_cvar sv_client_max_interp_ratio 1

**Comment by smounives** [comment]
你好，请问Tick解锁功能是否有门速度修复？
是否与这个TickrateFixes兼容？
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/TickrateFixes.sp#L84

**Comment by lakwsh** [comment]
> 你好，请问Tick解锁功能是否有门速度修复？ 是否与这个TickrateFixes兼容？ https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/TickrateFixes.sp#L84

没冲突，可以使用。
