### ISSUE TITLE
关于文中废弃的指令

### ISSUE THREAD

**Issue by cocosouth** [lakwsh/l4dtoolz#2]
![1](https://user-images.githubusercontent.com/103341584/165650161-494606ce-50ca-4e0b-9bf1-77b5822969eb.png)

早安！
原文以下指令废弃，为何仍然显示可以执行？
sm_cvar sv_minupdaterate 60
sm_cvar sv_maxupdaterate 100

**Comment by lakwsh** [comment]
嗯。。刚刚看了一下发现其实是写错了
废弃的指令是sv_minrate和sv_maxrate（设置了也不会有任何效果）
至于你说的这两个只需要设置一次即可，扩展里自动设置了
这些指令都是引擎本身提供的，所以就算废弃也依旧存在可以被修改
