### ISSUE TITLE
大厅匹配的问题

### ISSUE THREAD

**Issue by cocosouth** [lakwsh/l4dtoolz#3]
服务器是八人匹配服，有时候服务器会卡在1/8 或者7/8的状态，请问你能否解释如何处理的方法或者如何寻找制造该异常的问题

**Comment by lakwsh** [comment]
匹配功能由steam的master服务器提供，master服务器认为你服务器满人了你就卡7/8。目前无法处理，因为不知道匹配服务器是怎么写的。
