### ISSUE TITLE
no steam logon依然存在

### ISSUE THREAD

**Issue by cocosouth** [lakwsh/l4dtoolz#4]
根据对服务器日志的追踪，113版依然无法解决steam掉线问题，以及 即使暂时解决，玩家依然会timeout而掉线
![1](https://user-images.githubusercontent.com/103341584/167289718-5b776dda-c0fa-4023-ba00-fb223068e679.png)
![2](https://user-images.githubusercontent.com/103341584/167289721-733a32a0-6013-48c2-9a96-851ef2a26e8d.png)
![3](https://user-images.githubusercontent.com/103341584/167289723-594f14f8-1793-4dd9-9b26-1ffc545df0b5.png)

**Comment by lakwsh** [comment]
呃呃，这个刚刚看了一下113版写错了个判断，导致功能无法开启
至于timed out的话不属于同一类事件，还要研究一下

**Comment by lakwsh** [comment]
经研究，%s timed out这类提示属于网络连接问题
阻止此类事件会导致不可预期问题，故不做处理
将推出fix版修复No steam logon问题

**Comment by lakwsh** [comment]
新版本换了一种实现，有兴趣可以试试（v2.0.0+）
