### ISSUE TITLE
2155版偏移修复

### ISSUE THREAD

**Issue by lakwsh** [lakwsh/l4dtoolz#8]
社区接收后对steamapi进行了升级，导致sv_steam_bypass和sv_anti_sharing功能在2155版中不可用，如有需要请自行修改偏移值

**Comment by lakwsh** [comment]
linux
https://github.com/lakwsh/l4dtoolz/blob/a8822aeea8e7a3ca801dab22ba360272b0d5a641/signature_linux.h#L13
0xF
https://github.com/lakwsh/l4dtoolz/blob/a8822aeea8e7a3ca801dab22ba360272b0d5a641/signature_linux.h#L14
0x1D
https://github.com/lakwsh/l4dtoolz/blob/a8822aeea8e7a3ca801dab22ba360272b0d5a641/signature_linux.h#L15
0x25

windows
https://github.com/lakwsh/l4dtoolz/blob/a8822aeea8e7a3ca801dab22ba360272b0d5a641/signature_win32.h#L14
0x1D
https://github.com/lakwsh/l4dtoolz/blob/a8822aeea8e7a3ca801dab22ba360272b0d5a641/signature_win32.h#L15
0x21

**Comment by lakwsh** [comment]
以及，GetClientXUID改GetPlayerUserId

**Comment by oblivcheck** [comment]
对于我来说，如果不修改MakeFile就无法编译
https://github.com/oblivcheck/l4dtoolz/commit/62bb472e224e221fece6e706d171dec7e5155721#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52

**Comment by lakwsh** [comment]
见2155分支 https://github.com/lakwsh/l4dtoolz/tree/2155
